name: iOS Unit Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer

    - name: Install Dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Start iOS Simulator
      run: |
        device_id=$(xcrun simctl create MyTestDevice com.apple.CoreSimulator.SimDeviceType.iPhone-13, com.apple.CoreSimulator.SimRuntime.iOS-15-5)
        xcrun simctl boot $device_id

    - name: Run tests
      run: xcodebuild test -scheme musap-ios -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'
      
    - name: Shutdown iOS Simulator
      run: xcrun simctl shutdown $device_id

